[[headers]]
  for = "/og/*"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/cover/*"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=86400"
