name = "pulse"
compatibility_date = "2026-07-09"

[env.production]
name = "pulse-production"
compatibility_date = "2026-07-09"

[env.production.env_vars]
NODE_ENV = "production"

[env.preview]
name = "pulse-preview"
compatibility_date = "2026-07-09"

[env.preview.env_vars]
NODE_ENV = "preview"

[observability]
enabled = true

[triggers]
crons = []

[[kv_namespaces]]
binding = "SESSION"
id = "6f78704f3e674ad5b2e2365f11a2520e"

[env.production.kv_namespaces]
binding = "SESSION"
id = "6f78704f3e674ad5b2e2365f11a2520e"

[env.preview.kv_namespaces]
binding = "SESSION"
id = "6f78704f3e674ad5b2e2365f11a2520e"

[vars]
# 环境变量配置
NODE_ENV = "development"
